/* Ritual de Aumento de Salario (Ascenso al Segundo Grado, Compañero)
   Fuente: Liturgia del Segundo Grado, R∴L∴S∴ Hermes N.° 49.
   Todo el texto pronunciado se transcribe literal. Las entradas "accion"
   amplían y clarifican los movimientos en el Templo sin alterar palabras
   del guión; donde el guión no precisa la ubicación resultante de un
   desplazamiento, se marca la inferencia con (inferido). */

const RITUAL = [

/* ============ FASE 1 ============ */
{
  id:'apertura',
  title:'1. Paso de los Trabajos de Aprendiz a la Segunda Cámara',
  subtitle:'Apertura de la Cámara de Compañeros',
  entries:[
    {type:'accion', roles:['VM'], loc:'Oriente, en el trono', inferred:true,
     text:'La Logia se encuentra abierta en primer grado. Presentándose motivo para pasar al segundo, el Muy Ven∴ Maest∴ toma la palabra desde su trono en Oriente.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'QQ∴ HH∴ de ambas CCol∴ y de Or∴ Os anuncio que voy a suspender los trabajos de Apr∴ Por un solo golpe de mall∴'},
    {type:'accion', roles:['VM'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Los trabajos de Prim∴ Gr∴ Quedan suspensos; y vosotros HH∴ AApr∴ servíos cubrir el Temp∴'},
    {type:'accion', roles:['TODOS'], loc:'Columnas del Templo', inferred:true,
     text:'Todos los HH∴ están en sus puestos y de pie. El Muy Ven∴ Maest∴ da un golpe de mallete.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Guard∴ Temp∴ Int∴ Servíos avisar al Ext∴ Que voy a abrir la Log∴ de Comp∴ y que vele en consecuencia.'},
    {type:'accion', roles:['GT'], loc:'Puerta del Templo, hacia el exterior',
     text:'El Guard∴ Temp∴ sale por la puerta, avisa al Guarda Templo Exterior y regresa a su puesto junto a la puerta.'},
    {type:'dialogo', roles:['GT'], speakerLabel:'Guard∴ Temp∴',
     text:'El Guard∴ Temp∴ Ext∴ está avisado y seguimos a cubierto Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Gracias HH∴ míos; sentaos. HH∴ Prim∴ Y Seg∴ Vig∴ Servíos pedir a todos los presentes las PPal∴ de Pas∴ y Sag∴ del Gr∴ como yo lo haré en Or∴'},
    {type:'accion', roles:['P1V','P2V'], loc:'Columnas respectivas de cada Vigilante',
     text:'Los Vigilantes recorren visualmente sus columnas verificando la palabra de pase y la palabra sagrada de cada Hermano presente. Terminado el reconocimiento, habla el Segundo Vigilante.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴',
     text:'H∴ Prim∴ Vig∴ los HH∴ que decoran mi Col∴ son CComp∴ MMas∴'},
    {type:'accion', roles:['P2V'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴',
     text:'Muy Ven∴ Maest∴, Los HH∴ que hay en ambas CCol∴ son del Gr∴'},
    {type:'accion', roles:['P1V'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Lo mismo los de Or∴ Y así podemos proceder.'},
    {type:'accion', roles:['VM'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Sois Comp∴ H∴ Prim∴ Vig∴?'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Conozco la letra G'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Cómo la conocísteis, H∴ Seg∴ Vig∴?'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'Pasando de la regla a la Escuadra'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Para qué nos sirve la Escuadra H∴ Prim∴ Vig∴?'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Para hacer la piedra cúbica de punta, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿A qué hora acostumbran los CComp∴ MMas∴ abrir sus trabajos H∴ Seg∴ Vig∴?'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'A medio día'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Qué hora es, H∴ Prim∴ Vig∴?'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Medio día en punto, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Pues servíos anunciar en las Columnas, HH∴ VVig∴, como yo en Or∴ que voy a abrir los trabajos con los golpes misteriosos.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴',
     text:'H∴ Seg∴ Vig∴ y HH∴ de mi Col∴, nuestro Muy Ven∴ Maest∴ va a abrir los trabajos de Comp∴ por los golpes misteriosos.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴',
     text:'HH∴ de mi Col∴, nuestro Muy Ven∴ Maest∴ va a abrir los trabajos de Comp∴ por los golpes misteriosos. Anunciado H∴ Prim∴ Vig∴'},
    {type:'accion', roles:['P2V'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Anunciado Muy Ven∴ Maest∴'},
    {type:'accion', roles:['P1V'], text:'Da otro golpe de mallete.'},
    {type:'accion', roles:['VM','TODOS'], loc:'De pie, al orden, en sus respectivos puestos', inferred:true,
     text:'El Muy Ven∴ Maest∴ da cinco golpes de mallete, por tres y dos; todos se levantan poniéndose al orden.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'HH∴ al considerar que es medio día en punto, hora simbólica del principio de los trabajos de esta Cámara, debemos abrir la Log∴ en el Seg∴ Gr∴ suplicando al G∴ A∴ D∴ U∴ nos de luz para no perder los senderos de la Ciencia y la Virtud.'},
    {type:'dialogo', roles:['TODOS'], speakerLabel:'Todos los HH∴', text:'¡Así sea!'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Los trabajos de Comp∴ están abiertos. A mí HH∴'},
    {type:'accion', roles:['TODOS'], text:'Signo y batería, con la frase de:'},
    {type:'dialogo', roles:['TODOS'], speakerLabel:'Todos los HH∴', text:'¡Quien ilumina nuestra mente, Viva, Viva y siempre Viva!'}
  ]
},

/* ============ FASE 2 ============ */
{
  id:'peticion',
  title:'2. Petición de Aumento de Salario y Examen del Candidato',
  entries:[
    {type:'accion', roles:['VM'], loc:'Oriente, en el trono', inferred:true,
     text:'Terminados los trabajos ordinarios de la Logia y recibidos los Visitadores, el Muy Ven∴ Maest∴ da un golpe de mallete.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Si hay algún H∴ que quiera pedir aumento de salario para algún Apr∴ puede hacerlo.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'el H∴ {{NOMBRES}} se presenta esta noche como candidato al segundo grado; pero antes es preciso que nos dé pruebas de conocer el primero. A fin de saber si está apto, voy a nombrar una comisión que se encargue de examinarlo, y del informe que se nos rinda depende su ascenso.'},
    {type:'accion', roles:['PTE'], loc:'Fuera del Templo, en cámara de reflexión o antesala', inferred:true,
     text:'Se nombra una comisión ad hoc (encabezada por un Presidente de Comisión) que examina al candidato sobre los puntos del catecismo del Primer Grado, y ante todo sobre la perfección con que esté enterado de los signos, tocamientos, palabra sagrada y modo de darla, manera de entrar en Logia y como visitante en otra, y los deberes que ha contraído. Terminado el examen, el Presidente de la comisión entra al Templo.'},
    {type:'dialogo', roles:['PTE'], speakerLabel:'Presidente de la Comisión',
     text:'Muy Ven∴ Maest∴ el candidato (o candidatos) ha contestado satisfactoriamente en el examen que se le hizo.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'HH∴, el Apr∴ {{NOMBRES}} que aspira a obtener el segundo grado ha demostrado su aptitud en el correspondiente examen. ¿Teneis algo que exponer en contra de su solicitud?'},
    {type:'accion', roles:['VM'], text:'Si no se hiciere objeción, el Muy Ven∴ Maest∴ prosigue.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'HH∴ míos, vamos a conceder el ascenso acordado. H∴ Exp∴ Servíos preparar al candidato (o candidatos) y traedlo con el orden y recogimiento oportunos, tocando y saludando como Apr∴ HH∴ míos, silencio, respeto y atención; he aquí que lo que exige la Masonería en todas sus ceremonias.'}
  ]
},

/* ============ FASE 3 ============ */
{
  id:'entrada',
  title:'3. Preparación y Entrada del Candidato',
  entries:[
    {type:'accion', roles:['EXP'], loc:'Fuera del Templo, antesala', inferred:true,
     text:'El Experto sale del Templo. A uno de los candidatos le coloca el martillo en la mano derecha y la regla en la izquierda, descansando ésta sobre el hombro. En seguida los coloca a la puerta del Templo.'},
    {type:'accion', roles:['EXP'], loc:'Puerta de Occidente, por el exterior',
     text:'El Experto toca a la puerta como se toca en primer grado (toque de Aprendiz).'},
    {type:'accion', roles:['GT'], loc:'Puerta de Occidente, por el interior',
     text:'El Guarda Templo, que nunca responde cuando se toca en grado diferente del que se trabaja, mira por el postigo y, cerciorándose de que es el Experto con los graduantes, entreabre la puerta.'},
    {type:'dialogo', roles:['GT'], speakerLabel:'Guard∴ Temp∴', text:'Tocan como Apr∴, H∴ Seg∴ Vig∴'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'Tocan como Apr∴, H∴ Prim∴ Vig∴'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Tocan como Apr∴, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Servíos preguntar quién toca, H∴ Prim∴ Vig∴'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Servíos preguntar quién toca H∴ Seg∴ Vig∴'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'Servíos inquirir quién toca H∴ Guard∴ Temp∴'},
    {type:'dialogo', roles:['GT'], speakerLabel:'Guard∴ Temp∴ (dirigiéndose al Muy Ven∴ Maest∴)',
     text:'Es el H∴ Exp∴ Que conduce al candidato (o candidatos) que pide pasar de la Regla a la Escuadra'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Qué méritos han contraido para pretenderlo?'},
    {type:'dialogo', roles:['EXP'], speakerLabel:'H∴ Exp∴',
     text:'Simbólicamente ha trabajando los tres años que ordenan nuestros estatutos; ha cumplido su término labrando la piedra bruta, esto es, procurando perfeccionarse y se considera bastante instruído en su grado, para aspirar al superior.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'H∴ Guard∴ Temp∴, permitidle entrar.'},
    {type:'accion', roles:['EXP','GT'], loc:'Entre columnas, al orden',
     text:'El Guarda Templo abre la puerta. El Experto y el (los) candidato(s) entran y saludan como Aprendices, quedando al orden entre columnas.'},
    {type:'dialogo', roles:['EXP'], speakerLabel:'H∴ Exp∴', text:'Muy Ven∴ Maest∴ , el Apr∴ está entre CCol∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ mío, la confianza con que os presentais entre CComp∴ manifiesta que teneis la convicción de haber cumplido con vuestros deberes como Apr∴ Haced vuestro signo.'},
    {type:'accion', roles:['CAND'], loc:'Entre columnas', text:'El candidato hace su signo de Aprendiz.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Qué significa?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'Apr∴',
     text:'Es una parte del juramento que presté al ser recibido Masón, y significa que preferiré que me corten el cuello a revelar los secretos de la Masonería.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'¿Prometéis solemnemente, bajo la pena de vuestro primer juramento, guardar lo que se os revelará tan estrictamente como los demás secretos de la Masonería?'},
    {type:'accion', roles:['CAND'], text:'El candidato responde afirmativamente.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'¿Prometéis igualmente, bajo vuestra palabra de honor, preservar con firmeza en el propósito de ascenso?'},
    {type:'accion', roles:['CAND'], text:'El candidato responde afirmativamente.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Esto testifica Q∴ H∴ vuestra buena conducta y amor al trabajo. Se ha pedido para vos aumento de salario, y se os ha concedido; pero antes debemos sujetaros a las pruebas. Sentáos. La Masonería es una institución fundada en la moral, que tiene principios: AMOR FRATERNAL, SOCORRO y VERDAD; que busca el prefeccionamiento de los que a ella pertenecen, a fin de que, llegando a ser virtuosos y fuertes, puedan trabajar por el bien de la familia, de la sociedad, de la Patria y del progreso humano. Es el lazo que une a los hombres de todos los países, de cualquiera religión que sean, y es un refugio en las tempestades y en las desgracias del orden social. Para hacer de sus adeptos hombres ilustrados y capaces de realizar los sublimes ideales que persigue, las vías que adopta son diferentes, según el grado en que está el hermano. En el de Apr∴ le somete a pruebas que pongan en claro su relativa instrucción y su carácter, observando si su conducta tiende a corregirse a sí mismo; a mostrar su afecto fraternal para con los demás, su buena voluntad a la institución y la sinceridad con que procede. En el de Comp∴ procura que se instruya y fortalezca elevando sus ideales por el bien. El trabajo, a ley inviolable de la humanidad entera, es la palanca poderosa en este grado, como en todas las circunstancias de la vida. La Masonería, lo mismo que la madre tierra, no ofrece sus tesoros sino a los que saben cultivarla. “BUSCAD Y ENCONTRAREIS”'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Cuando os iniciásteis Apr∴ nacísteis en realidad a la VERDADERA LUZ de la inteligencia, y vísteis que había un pueblo verdaderamente libre. Estamos seguros que el grado de Comp∴ os satisfacerá, porque en él comienza a abrirse el arca de nuestros MISTERIOS, y gozaréis al hallaros entre hombres libres y de buena fe, que os harán partícipe de sus conocimientos. HH∴ míos, aumentemos la luz a este Apr∴ Ponéos de pie. Y vos H∴ Exp∴, conducid al candidato frente al cuadro del Temp: de Salomón.'},
    {type:'accion', roles:['VM','EXP'], loc:'Norte del Templo, frente al cuadro del Templo de Salomón',
     text:'El Muy Ven∴ Maest∴ baja del trono y va donde está el cuadro, a la vez que el Experto conduce al candidato al mismo lugar y enciende las cinco luces del candelabro.'}
  ]
},

/* ============ FASE 4: los cinco viajes ============ */
{
  id:'viajes',
  title:'4. Los Cinco Viajes',
  subtitle:'Instrucción simbólica junto al cuadro del Templo de Salomón',
  entries:[
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Apr∴ ahí teneís el Temp∴ de la Sabiduría. Este Temp∴ que figura el de Salomón, es el emblema del templo moral que debéis levantar en vuestro corazón. Para erigir semejante templo moral os han de servir de piedras, preciosamente labradas, las verdades sublimes que nos legaron todos los que han luchado por el enaltecimiento de la Virtud y los progresos de la Ciencia. Mirad al pie del templo esos instrumentos, emblema del trabajo constante que debéis simbólicamente emplear en el estudio del perfeccionamiento que anhelamos. Con ellos vais a dar cinco viajes alrededor de la Logia, recordando así los cinco años que pasaban en el más severo aprendizaje, los discípulos de las antiguas escuelas filosóficas, de donde se desprenden las verdades hoy conocidas y aceptadas universalmente.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Exp∴ quitad la regla al graduante; ponedle el martillo en la mano derecha y el cincel en la izquierda haciéndolo viajar por el Norte hasta Or∴ y de allí al Med∴'},
    {type:'accion', roles:['VM'], loc:'Oriente, de vuelta al trono',
     text:'Dicho lo anterior, el Muy Ven∴ Maest∴ vuelve al trono.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Sentáos HH∴'},
    {type:'accion', roles:['EXP','CAND'], loc:'Primer viaje: por el Norte hasta Oriente y de allí al Mediodía, hasta la mesa de instrumentos al pie del cuadro',
     text:'El Experto ejecuta lo mandado en unión del graduante, portando éste el martillo y el cincel, haciendo alto al pie del cuadro. Si son varios los graduantes, uno lleva los instrumentos y los demás le siguen; si hay música, ésta se toca durante el viaje. Al terminar, el Experto y el graduante se sientan juntos a la mesa de instrumentos, dejando allí los que portaba el candidato.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'Muy Ven∴ Maest∴ el primer viaje ha terminado.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Según la historia alegórica de la construcción del Temp∴, los AApr∴ admitidos en las obras, empleaban el primer año en desbastar con el cincel y el martillo los minerales y maderas de la fábrica, y hasta que conocían bien sus distintas cualidades, no se les destinaba a trabajos superiores. Esto quiere decir que necesitais aprender y pulir vuestra inteligencia para hallaros en aptitud de ser útil a la Humanidad y a vos mismo. El cinel significa la constancia en la perfección; y el martillo la sumisión de la fuerza bruta a la inteligencia. Se os hizo viajar por los cuatro puntos cardinales, significándoos que, cualesquiera que sean los tropiezos que encontraréis en vuestro camino, no desmayéis en vuestra empresa. La cadena que rodea el Temp∴ es el Simb∴de la Fraternidad que une a todos los MMas∴ del Universo. El mosaico de cuadros blancos y negros, son los bienes y los males por que tenéis que pasar en vuestra peregrinación. Levantáos y dadle el signo de Apr∴ al H∴ Exp∴'},
    {type:'accion', roles:['CAND'], text:'El candidato hace el signo de Aprendiz al Experto.'},
    {type:'dialogo', roles:['EXP'], speakerLabel:'Exp∴', text:'Perfecto, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Exp∴ entegad el Compás y la Regla al graduante y dirigidle en su segundo viaje para que vea el Triángulo del frontispicio del Temp∴ la Estrella que le embellece, y sepa el significado de la letra “G”.'},
    {type:'accion', roles:['EXP','CAND'], loc:'Segundo viaje: misma dirección que el anterior, hasta el trono del Segundo Vigilante (Occidente, columna Sur)', inferred:true,
     text:'El Experto ejecuta el viaje en la misma dirección que el anterior, portando el graduante el Compás y la Regla, haciendo alto al pie del trono del Segundo Vigilante.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'Muy Ven∴ Maest∴ el segundo viaje ha terminado.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Sentáos, HH∴ míos.'},
    {type:'accion', roles:['EXP'], text:'El Experto recoge el Compás, dejando la Regla al graduante, y se sientan.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'En este segundo viaje llevásteis el Compás y la Regla, instrumentos proncipales de las obras humanas. El primero traza el círculo, la más hermosa de las figuras, y muestra el centro, la igualdad de los radios, el valor del diámetro y lo justo de todas las medidas. Es el regulador universal y emblema de la Lógica, regulador por excelencia de lo cierto y lo falso, que nos enseña a discurrir con precisión, clasificar nuestros conocimientos y deducir consecuencias exactas. Con él y la Regla formamos las figuras geométricas, obtenems líneas y medidas perfectas; en una palabra, hacemos el Triángulo, signo venerado en todas las edades, porque es el de la fuerza y el Orden. Sería imposible comprender ni demostrar sin él las Leyes del Universo, ni construir obras duraderas. Las propiedades del Triángulo constituyen la Trigonometría; aplicada a los cuerpos celestes, son la base de la Agronomía, al curso de un buque en el Océano, de la Navegación, a la construcción del edificio, de la Arquitectura. Es el amla de las ciencias y el símbolo de un principio. Encontrarás el Triángulo en el frontispicio de nuestro Temp∴ porque es la Verdad, y simboliza las leyes de la Materia. Dentro del él brilla la Estrella flamígera, astro místico de la razón que ilumina al Comp∴ y cuya luz inextinguible disipa las tinieblas de la ignorancia. En su centro se encuentra la letra “G”, emblema del GENIO del hombre, a quien aquella dirige en el camino de la Sabiduría, aclarándole el espacio inmenso que tiene que recorrer para la posesión de todas las verdades. Recuerda a la GEOMETRÍA, piedra fundamental de las ciencias y de las artes; y a la GENERACIÓN, fuente de vida de todos los seres. Así la “G”, la Estrella y el Triángulo, representan a Dios, (GOD en inglés), padre de todo lo existente; la RAZÓN, que guía al hombre en el camino de la vida, y la SABIDURÍA, que conduce al conocimiento de los arcanos de la naturaleza. Levantáos y dad el Toc∴ De Apr∴ al Seg∴ Vig∴'},
    {type:'accion', roles:['CAND','P2V'], text:'El candidato da el toque de Aprendiz al Segundo Vigilante.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'Perfecto, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Servíos, H∴ Exp∴ entregar al Apr∴ la palanca, además de la Regla que ya tiene, y guiadle en el tercer viaje para que examine las CCol∴ del Temp∴ y vea los nombres que las caracterizan.'},
    {type:'accion', roles:['EXP','CAND'], loc:'Tercer viaje: hasta el trono del Primer Vigilante (Occidente, columna Norte)', inferred:true,
     text:'El Experto ejecuta el viaje, portando el graduante la palanca y la Regla, y va a parar al trono del Primer Vigilante.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'El tercer viaje ha terminado, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Sentáos'},
    {type:'accion', roles:['EXP'], text:'El Experto recoge la palanca, deja la Regla al graduante, y se sientan.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'La Virtud no deba jamás abandonarse; por eso en este viaje seguís llevando la Regla. La palanca, que sirve para levantar pesos, cuya acción niguno resiste, es el emblema del poder inmenso que el hombre adquiere aplicando los principios de la Ciencia a los actos que su fuerza individual no lograría por sí sola; y en el sentido Muy profundo del tercer viaje, representa el poder que alcanza la Razón, con el auxilio de los estidios filosóficos y morales a que os han preparado las ciencias físicas. Así, H∴ la Palanca y la Regla reasumen el concepto de las dos palabras: CIENCIA y VIRTUD, que nos dan la fortaleza necesaria para soportar y vencer los trabajos de la vida, así como los halagos del vicio, sin que jamás un temor cobarde nos precipite a la desesperación. Las CCol∴ del frontispicio del Temp∴ tienen LIRIOS, símbolos de nuestra pureza de acción. Y GRANADAS, que con sus innumerables granos, figuran el conjunto de los MMas∴ Sostienen los globos celeste y terrestre para expresar que, por la CIENCIA y la VIRTUD, que leeis en su centro, el hombre llenará los fines para los que fue creado. Sabéis como Apr∴ lo que es VIRTUD. Por CIENCIA entendemos “un conjunto de hechos de los cuales se han deducido principios generales”. Es el fundamento del arte, porque éste es: “LA APLICACIÓN DE AQUELLOS PRINCIPIOS AL USO DE LA VIDA”. Levantáos y dad la Pal∴ Sag∴ al Prim∴ Vig∴'},
    {type:'accion', roles:['CAND','P1V'], text:'El candidato da la Palabra Sagrada al Primer Vigilante.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Justa y perfecta, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Exp∴ entregad al graduante la Escuadra, para que con ella y la Regla de su cuarto viaje y examine la Piedra Cúbica de Punta y los cinco escalones del segundo tramo dela escalera del Temp∴'},
    {type:'accion', roles:['EXP','CAND'], loc:'Cuarto viaje: piedra cúbica al pie de la Columna J, y cuadro del Templo (segundo tramo de la escalera)',
     text:'El Experto ejecuta el cuarto viaje con el graduante, portando éste la Escuadra y la Regla; le muestra la piedra cúbica que está al pie de la Columna “J”, y lo lleva al cuadro para que lea los letreros del segundo tramo de la escalera del Templo.'},
    {type:'dialogo', roles:['EXP'], speakerLabel:'Exp∴', text:'El cuarto viaje ha terminado, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Sentáos, HH∴ míos.'},
    {type:'accion', roles:['EXP'], loc:'Mesa de instrumentos, al pie del cuadro',
     text:'El Experto recoge los instrumentos, los pone sobre la mesa y se sienta.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'En este cuarto viaje llevásteis una Escuadra además de la Regla. La primera simboliza la Igualdad que debe reinar entre los hombres, y es principio que el masón no debe desatender jamás, y la segunda es emblema de la Justicia y Rectitud que han de normar todos nuestros actos, si queremos merecer el respeto y la consideración de nuestros semejantes. Para ejercitar esas prácticas y adquirir las demás virtudes que deben adornar a todo buen masón, yo os exhorto a que cultivéis vuestro espíritu, medio seguro de enaltecer los sentimientos de vuestro corazón. Cualquiera que sea el honesto trabajo a que os dediquéis en la vida profana, mejoradlo con empeño, que así laboraréis por vuestro bien y el de vuestra familia, contribuyendo al adelanto común, que es el progreso en las diversas manifestaciones del trabajo honrado. Así os sentiréis capaz de procurar subir las cinco gradas del segundo tramo en esa escalinata que, como miráis, representa INTELIGENCIA, RECTITUD, VALOR, PRUDENCIA y FILANTROPÍA, que caracterizan el grado de Compañero. INTELIGENCIA, para comprender la misión noble de la vida; RECTITUD, para juzgar con pureza de sentimiento y elevación de criterio nuestras propias acciones primero, y luego las de los demás; VALOR, para no deSeg∴ Vig∴iarse del sendero que la virtud nos marca, aunque ello demande lucha; PRUDENCIA, para no exponer sin necesidad los intereses nobles que lleguemos a representar en cualquier circunstancia, y FILANTROPÍA, para cumplir debidamente el más alto fin de nuestra Institución. Filantropía que es amor para los demás, es piedad para los que sufren y es caridad para los necesitados. H∴ Exp∴ haced que el graduante ejecute su último trabajo como Apr∴ y detenedle como el sol en el solsticio del Estío.'},
    {type:'accion', roles:['EXP','CAND'], loc:'Piedra bruta al pie de la Columna B',
     text:'El Experto lleva al graduante junto a la piedra bruta que se halla colocada al pie de la Columna “B”, le entrega el martillo y le hace dar tres golpes sobre ella. Luego le coloca junto al Segundo Vigilante.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴',
     text:'Muy Ven∴ Maest∴ el graduante ha hecho su último trabajo de Apr∴ y le concede el pase de mi Col∴ “B” a la Col∴ “J”.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Exp∴ haced que el graduante dé su último viaje. En pie y al orden HH∴'},
    {type:'accion', roles:['VM'], text:'Da un golpe de mallete.'},
    {type:'accion', roles:['EXP','CAND'], loc:'Quinto viaje: hacia atrás, del Oriente al Norte y de allí a Occidente, hasta el pie del trono del Primer Vigilante',
     text:'El Experto coge al graduante por el brazo izquierdo, le hace dar la espalda al Oriente, le coloca la punta de la espada en el pecho (única espada empuñada en este viaje, portada por el Experto) y le hace andar hacia atrás hasta Oriente, y de allí por el Norte a Occidente, hasta el pie del trono del Primer Vigilante. Si hay música, ésta toca una marcha fúnebre, que cesa al llegar el graduante a Occidente. En este momento el Experto deja al candidato, que no ha de llevar instrumento alguno.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Terminó el quinto y último viaje, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Sentáos QQ∴ HH∴ – H∴ Apr∴ este último viaje tiene tres significados: uno astronómico, otro moral y el último secreto. Aludiendo al primero, dispuse que os detuviérais en el punto en el que el sol RETROGRADA, para que imitáseis su movimiento. Debéis saber que en la antigüedad la Astronomía se consideraba como la más sublime de las ciencias, y a su estudio se dedicaba el año del aprendizaje. En cuanto al segundo, o al moral, notaríais que en los viajes anteriores llevábais intrumentos de trabajo, lo que supone que los empleábais y, por consecuencia, que siempre marchábais adelante; mas en éste estábais ocioso, en el concepto de que ningún instrumento portábais y, por lo mismo, en vez de seguir con el progreso, RETROCEDÍSTEIS al barbarismo. EL ÚLTIMO SIGNIFICADO SE REVELA EN LOGIA Y SÓLO LO POSEEN LOS MASONES ESCOCESES.'},
    {type:'accion', roles:['VM'], text:'El Muy Ven∴ Maest∴ explica en Logia el último significado, conforme a las disposiciones propias del Taller.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Ya conocéis vuestras obligaciones: para ser digno del Gr∴ de Comp∴ debéis trabajar incesantemente en vuestra perfección física, moral e intelectual. Os recibimos Apr∴ sólo porque érais hombre libre de preocupaciones y honrado; ahora, ya sabéis que es indispensable el cultivo de vuestra inteligencia para constituíros en elemento de progreso, y que el trabajo es el guardián de la virtud y el que hace vuestra felicidad y la de vuestros semejantes. Estudiad los derechos y deberes que son inherentes a la naturaleza humana, y que osn necesarios para guiardar el equilibrio que requiere la conservación de las sociedades. Todo derecho es inseparable de un deber, y habréis de respetar el derecho ajeno, si queréis que se reconozca el vuestro. Antes de reclamar derechos, tnéis que cumplir las obligaciones que os impone el medio socual en el que vivís. En cuanto a la parte masónica, habéis ingresado a la Seg∴ Cámara, en la que, a diferencia de la primera, no basta la corrección de conducta, sino que, en pleno desempeño de funciones, tendréis que cumplir las comisiones que os dé la Log∴ directamente, o las emanadas de la Gr∴ Log∴ de que dependemos y desempeñar, en Ten∴ y fuera de ella, los oficios de vuestro grado, que se os designen oportunamente. Tal es la elevación de miras, el goce de funciones y los nuevos deberes del Comp∴ Masón, que dignamente ha merecido el ascenso.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'HH∴ en pie, y decid todos conmigo: “QUE ELA MOR NOS UNA, QUE EL DEBER SEA NUESTRA NORMA, QUE LA EXACTITUD EN CUMPLIRLO NOS DISTINGA, EN TODOS NUESTROS NOBLES TRABAJOS, COMO A LOS LUCHADORES POR EL BIEN DE LA HUMANIDAD”.'},
    {type:'dialogo', roles:['TODOS'], speakerLabel:'Todos los HH∴',
     text:'“QUE EL AMOR NOS UNA, QUE EL DEBER SEA NUESTRA NORMA, QUE LA EXACTITUD EN CUMPLIRLO NOS DISTINGA, EN TODOS NUESTROS NOBLES TRABAJOS, COMO A LOS LUCHADORES POR EL BIEN DE LA HUMANIDAD”'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ MAEST∴ DE CER∴, servíos conducir al candidato ante el Altar, y vosotros acompañadme al acto solemne del juramento.'}
  ]
},

/* ============ FASE 5: juramento ============ */
{
  id:'juramento',
  title:'5. Juramento del Compañero y Proclamación',
  entries:[
    {type:'accion', roles:['MC','TODOS','EXP'], loc:'Centro del Templo, alrededor del Altar de los Juramentos',
     text:'El Maestro de Ceremonias conduce al candidato ante el Altar. Todos los HH∴ se levantan y forman círculo alrededor del Altar. Los dos Expertos —únicos, junto con el Guarda Templo, autorizados a empuñar espada— forman sobre el graduante la bóveda de acero con sus espadas.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴ (al graduante)', text:'Repetid conmigo:'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'Juramento del Compañero — {{NOMBRES}}',
     text:'Yo, {{NOMBRES}} de mi entera y libre voluntad; en presencia del G∴ A∴ D∴ U∴ y de esta Resp∴ Log∴ juro por mi honor no revelar jamás ninguno de los secretos, misterios y actos de los Compañeros Masones a los profanos y AApr∴ Juro igualmente obedecer los estatutos de la Orden, el Reglamento de esta Corporación y las disposiciones de su Ven: Juro también servir a todos los HH∴ como leal Comp∴ defenderlos, avisarles y procurar liberarlos de todo peligro, y por último, juro hacer lo posible por mejorar mi honesto modo de vivir, y dedicar el tiempo que no emplee en el trabajo indispensable a mi existencia y a la de mi familia, al estudio, para adquirir la Inteligencia, la Rectitud, el Valor, la Prudencia y la Filantropía que me hagan digno del nombre de Comp∴ Y antes que faltar a todo o en parte a estos solemnes compromisos, quiero que se me arranque el corazón y se arroje a los buitres para que les sirva de pasto.'},
    {type:'accion', roles:['VM'], loc:'Junto al Altar, sobre la cabeza del graduante',
     text:'El Muy Ven∴ Maest∴ levanta la espada (tomada para este acto exclusivo del juramento; ninguna otra dignidad u oficial distinto del Guarda Templo y los Expertos porta espada en el ritual), la toma con la mano izquierda, la tiende sobre la cabeza del graduante, y toma el mazo con la otra mano.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'A∴ L∴ G∴ D∴ G∴ A∴ D∴ U∴ bajo los auspicious de la Gr∴ Log∴ de que dependemos, y en virtud de los poderes que esta Resp∴ Log∴ me tiene conferidos, os declaro, nombro y constituyo Comp∴ Mas∴ y miembro de esta Seg∴ Cam∴ Simb∴ Por los golpes misteriosos del grado.'},
    {type:'accion', roles:['VM'], text:'Da cinco golpes con el mallete sobre la hoja de la espada.'},
    {type:'accion', roles:['VM'], loc:'Oriente, de vuelta al trono',
     text:'El Muy Ven∴ Maest∴ vuelve al trono.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Sentáos HH∴ y vos, H∴ Maest∴ de Cer∴ conducid al neófito a Or∴ para instruirlo.'},
    {type:'accion', roles:['MC','VM'], loc:'Oriente, junto al Muy Ven∴ Maest∴',
     text:'Se ejecuta lo mandado; el Muy Ven∴ Maest∴ baja del trono y se dirige al graduante para instruirlo.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Los caracteres de este grado son los siguientes: se toca la puerta así'},
    {type:'accion', roles:['VM'], text:'Lo ejecuta (toque del grado).'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'La marcha es la de cinco escuadras:'},
    {type:'accion', roles:['VM'], text:'La enseña.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Hay dos signos, el de orden o de tres escuadras, y el pectoral o de saludo.'},
    {type:'accion', roles:['VM'], text:'Los hace.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'El tocamiento se da de este modo:'},
    {type:'accion', roles:['VM'], text:'Le muestra el tocamiento.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Al entrar a la Log∴ daréis la Pal∴ De Pase al Guard∴ Temp∴'},
    {type:'accion', roles:['VM'], text:'Se la dice en voz baja.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Significa ENCARGADO DE LA PALABRA.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'La Pal∴ Sag∴ se da silabeando, porque ya sabéis deletrear y tenéis cinco años de edad, y es:'},
    {type:'accion', roles:['VM'], text:'Se la indica en voz baja.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Equivale a ESTABILIDAD. Las baterías se dan de esta suerte'},
    {type:'accion', roles:['VM'], text:'Las efectúa, distinguiendo la de júbilo de la de duelo.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Los CComp∴ Llevan el mandil con la solapa caída y la ezquina inferior izquierda doblada hacia arriba. El instrumento que manejan especialmentre es la Escuadra, símbolo de la igualdad que nos nivela, y su número característico es el cinco, que contiene todo el simbolismo del grado. El estudio más detenido de las alegorías de esta Cámara, os dará a conocer tods las bellezas morales e intelectuales que encierra. Meditad mucho H∴ mío, acerca de lo que se os ha enseñado. Este grado es la PIEDRA ANGULAR del edificio masónico, levantadlo a la ciencia y a la virtud. H∴ Maest∴ de Cer∴ conducid al candidato fuera del Temp∴ para que llame y entre como Comp∴ dando al Guard∴ Temp∴ la Pal∴ De Pas∴ y se salude a las tres LLuc∴'},
    {type:'accion', roles:['VM'], loc:'Oriente, en el trono', inferred:true, text:'El Muy Ven∴ Maest∴ se sienta.'},
    {type:'accion', roles:['MC','CAND'], loc:'Fuera del Templo, puerta de Occidente',
     text:'El Maestro de Ceremonias conduce al candidato fuera del Templo. Este llama a la puerta y entra ya como Compañero, dando al Guarda Templo la Palabra de Pase y saludando a las tres luces del Templo.'},
    {type:'dialogo', roles:['MC'], speakerLabel:'Maest∴ de Cer∴',
     text:'Muy Ven∴ Maest∴ , el candidato ha cumplido vuestra orden y se halla entre CCol∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Maest∴ de Cer∴ servíos proclamarlo Comp∴ Masón en Or∴ Occ∴ y Med∴, en pie y al orden HH∴'},
    {type:'accion', roles:['MC'], loc:'Oriente, Occidente y Mediodía sucesivamente',
     text:'El Maestro de Ceremonias hace la proclamación en las tres direcciones del Templo: Oriente, Occidente y Mediodía.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Queda pues, reconocido, admitido y proclamado Comp∴ Mas∴ el H∴ {{NOMBRES}}. Acompañadme todos a saludarle.'},
    {type:'accion', roles:['TODOS'], text:'Se hace el saludo del grado y luego se sientan todos.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'H∴ Orad∴ Tenéis la palabra para celebrar este acto e instruir al Candidato en su nuevo grado.'},
    {type:'accion', roles:['OR'], loc:'Oriente, tribuna del Orador', inferred:true,
     text:'El Orador pronuncia su discurso alusivo al acto y a la instrucción del nuevo Compañero. Terminado el discurso, se le aplaude, se concede la palabra a quien la pida, y se continúan los trabajos hasta la clausura, o se desciende al grado de Aprendiz si así procede.'}
  ]
},

/* ============ FASE 6: catecismo ============ */
{
  id:'catecismo',
  title:'6. Catecismo del Compañero',
  subtitle:'Instrucción complementaria — puede omitirse o reservarse para otra Tenida de instrucción',
  entries:[
    {type:'dialogo', roles:['VM'], speakerLabel:'PREGUNTA', text:'¿Sois compañero?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'RESPUESTA', text:'Conozco la letra “G”, quinta consonante del alfabeto.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué significa esa letra?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Tiene varias interpretaciones: Es la inicial del G∴ A∴ D∴ U∴ en el idioma de diversos pueblos que derivaron el nombre de Dios de la palabra hebrea HIOAH. Ser que se considera como la fuente de donde emana la luz que ilumina las inteligencias con las llamas del Genio, para hacerles descubrir la Verdad inmanente. Es la Geometría, alma de las ciencias, creadora de las artes y clave en que se decansa el conocimiento de la naturaleza. Y es la GENERACIÓN, misterio sublime que guarda el enigma de la vida; productora constante de transformaciones que sostienen y conservan la materia. Y foco, en el mundo de la idea, que alimenta incesantemente el Progreso de la Humanidad.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cómo llegásteis a comprender esto?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Haciendo cinco viajes, en los que aprendí a emplear las facultades con que me dotó la Naturaleza.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué palabra las resume?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Educación'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Y cómo se adquiere esa educación?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Con el estudio y el hábito de vencer las dificultades de la vida, y la necesidad constante de prever los acontecimientos que con nosotros se relacionan.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué simbolizan aquellos viajes?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Los cinco años de trabajo físico e intelectual, que precedían a la iniciación en los primeros tiempos.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Y porqué no se exigen ahora?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Porque el grado de Comp∴ que hoy se da es simbólico, esto es, indicador de los estudios indispensables que ha de hacer el que quiera poseerle.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué significan moralmente los instrumentos que se pusieron en vuestras manos durante los viajes?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'EL CINCEL, es el emblema de la constancia en la perfección; el COMPÁS da la regularidad en la conducta; la PALANCA, del poder de la razón para dominar las pasiones, y la ESCUDRA, de la igualdad que ha de reinar en todos los hombres.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Para qué sirven esos instrumentos?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Simbólicamente, para labrar la piedra cúbica de punta, ese primer sólido perfecto de tan importante uso en las obras materiales, porque es la angular del edificio; haciéndome así entender tal símbolo, la labor intelectual a que el Comp∴ tiene que consagrarse en el templo de la Virtud y del Progreso.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué es la Piedra Cúbica para los Compañeros?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Es aquella en la cual se considera que prepara y afila sus herramientas, y simboliza los progresos que debe hacer en la Institución y en sus relaciones con los HH∴ siendo el Sólido más perfecto, la Piedra angular del templo de la Sabiduría, porque encierra todos los conocimientos que preceden a una perfecta instrucción; y termina en pirámide, símbolo del fuego, para representar al alma aspirando a su origen.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué se compara al Apr∴ con la piedra tosca y al Comp∴ con la cúbica de punta?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Porque aquel está informe como la primara, y éste pronto a servir, a semejanza de la segunda y además, tiende a reunir las virtudes que señalan los números de sus caras, elevando su esfuerzo al cuadrado por su potencia, a fin de llegar al máximo desarrollo en el libre espacio del pensamiento sano y de la acción bienechora.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué es la Estrella Flamígera?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Es el símbolo del magnetismo terrestre, de esa acción invisible que crea y sostiene nuestra vida sobre el globo; del centro maravilloso, de la fuerza propulsora, atractiva y reguladora del movimiento uiniversal; es el emblema de la naturaleza, fuente inagotable de vida, destello del fuego sagrado y semilla universal de los seres. Significa, además, la razón, que liberta al alma de los prejuicios, para elevarla a las sublimes concepciones de la verdad, y está iluminada, porque el ilustre iniciado (Pitágoras) recomendó no hablar sin luz de las cosas divinas.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué brilla en este grado la Estrella Flamígera?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Porque este Gr∴ rpresenta la segunda estación del año, en que el padre de la luz llega a su más alta exaltación, desde donde parece que lanza lenguas de fuego dando la palabra osea la facultad de producir, a todos los seres vivientes; por eso las cinco puntas de la estrella, como los cinco viajes del grado, representan los cinco meses de reproducción de la naturaleza, después de los cuales la palabra se pierde. Los antiguos filósofos, viendo en el hombre un compendio del Universo, le llamaron MICROCOSMOS (pequeño mundo), imagen de la estrella flamígera, que representaban por una cabeza humana, cuyo rostro indicaba el ángulo superior, los otros cuatro miembros separados, los otros cuatro ángulos, y en el centro la letra “G”.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué significa el cordón anudado?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Esos nudos entrelazados, que sin interrumpirse, forman el cordón anudado de nuestros templos, son imagen de la unión fraternal que liga con cadena indisoluble a todos los masones del globo, sin distinción de clases ni condiciones. Su entrelazada simboliza también el secreto que debe rodear nuestros misterios. Su extensión circular y sin discontinuidad indica que el imperio de la Masonería, o el reino de la Virtud, comprende el universo en el símbolo de cada Log∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué reemplazan en las CCol∴ las esferas a las granadas?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Porque en este grado científico esas esferas simbolizan la armonía del universo, y designan el género de estudio al que el Comp∴ debe dedicarse.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cómo se os recibió Comp∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Pasando de la Col∴ “B” donde me sentaba como Apr∴ a la Col∴ “J” o sea de la aspiración de la ciencia a la aspiración sublime de la virtud.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Por dónde se sube al Temp∴ de salomón que sirve a nuestro simbolismo?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Por una escalera de caracol, dividida en tres tramos, que recorren los Aprendices, los Compañeros y los Maestros.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Por qué puerta subísteis?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Por la de Occ∴ pues al Or∴ está el Santuario, dondo sólo pueden entrar los Maestros.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué vísteis a los lados de la puerta?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Dos grandes CCol∴ de bronce, de dieciocho codos de altura y doce de circunferencia.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué esa deformidad en la obra maestra?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Para demostrar al mundo, desde los umbrales del Temp∴ de la Verdad, que la perfección es imposible y la elegancia transitoria, por lo que sólo debe aspirarse a la ciencia y a la virtud, símbolos de las columnas, las cuales son accesibles y eternas una vez que se alcanzan.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cuál es el diámetro de las CCol∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Cuatro codos'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Y su grueso?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Cuatro pulgadas'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Con qué fin estaban huecas?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Con el de guardar las herramientas de los AApr∴ y CComp∴ junto con el tesoro que pagaba su salario.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué adornos tenían?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Un ancho capitel hermoseado con redes, sembrado de azucenas, lirios y granadas, y coronado de un globo terrestre en la red del Norte, y otro celeste en la del Sur, en los que descansaba el triángulo, símbolo del Eterno.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué representan esos objetos?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'La red representaba la unión, los lirios el candor, las azucenas la pureza de nuestros corazones, las granadas los innumerables bienes que esas cualidades nos proporcionan, y los globos la universalidad de la Masonería y su ideal sublime.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué había alrededor del Temp∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Una cadena circuía, y un pavimento de mosaico enlozaba el gran pórtico, representando aquella el vínculo fraternal que nos une para sostenernos en el terreno peligroso de la vida y dirigirnos hacia el bien, tan exactamente repartido como el mal, a semejanza de los colores del segundo.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué forma tenía el Temp∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'La de un cuadrilongo'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿En qué sentido estaba su longitud?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'De Oriente a Occidente'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Su anchura?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'De Septentrión a Mediodía'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Y su alto?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Os diré que era de pies, toesas y codos innumerables, para significaros que se elevaba al cielo.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué le cubría?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Un dosel azul sembrado de estrellas'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿En dónde se apoyaba?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'En tres grandes pilares de forma triangular.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué nombre tienen?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Sabiduría, Fuerza y Unión.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué los llamáis así?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Porque la Sabiduría inventa, la Fuerza ejecuta y la Unión asegura el resultado.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cuál es la profundidad de vuesta Log∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'De la superficie de la tierra al centro.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué respondéis de esa manera?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Para dar a entender que la Log∴ debe reputarse que es el universo en que la Masonería extiene sus trabajos de perfeccionamiento para sus miembros y sus labores trascendentales para el progreso humano.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿En dónde se sientan los compañeros?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Al Mediodía.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Porqué?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Porque la luz que resplandece en él es simbólica de las ciencias en que se inspira la doctrina del Comp∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cómo reciben su pago los Compañeros?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Dando los SSig∴, TToc∴ Y PPal∴ del Gr∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cómo se hace el Sig∴ de orden?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'¡Vedle!'},
    {type:'accion', roles:['CAND'], text:'Se levanta y queda al orden.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cómo se llama el Sig∴ de saludo?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Pectoral'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿De qué modo se ejecuta?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Así'},
    {type:'accion', roles:['CAND'], text:'Lo hace, en seguida se sienta.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cómo se da la Pal∴ de Pas∴ y qué significa?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'Al oído y al entrar en Log∴ y significa “Fruto de Sabiduría” o “Encargado de la Palabra”, porque antes no se concedía ésta sino a los expertos depués de cinco años de estudio.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué significa la Pal∴ Sag∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Estabilidad'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué significa la oblicuidad final de la marcha del Comp∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Que el Comp∴ puede ir hacia el Norte o hacia el Mediodía, y viajar por todas paretes para instruirse e instruir a los demás.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Qué simboliza el grado de Comp∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'El de trabajador, el de luchador en estado pleno, el de cooperador a los elevados empeños del Maestro, sirviendo en comisiones y oficios de la correspondiente Log∴, el de obrero que está en aptitud de trabajar a conciencia con voluntad, con el esfuerzo y exactitud, ayudado por la INTELIGENCIA propia para discernir, por la RECTITUD, para seguir el mejor sendero; por el VALOR, para afrontar los peligros y vencer obstrucciones, por la PRUDENCIA, para no lanzarse a la aventura insensata, y por la FILANTROPÍA, para prodigar el bien hasta entregarse en holocausto por las grandes causas del humano progreso. Este grado también simboliza el estudio del hombre y la manera de educarle para que conozca sus deberes y derechos y sepa emplear todos los recursos de que le dotó la naturaleza, se libre de la esclavitud de los instintos y viva por la inteligencia; de aquí viene el nombre de INICIACIÓN PERFECTA, que le daban los antiguos.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Y cabe ese programa en nuestro grado?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'No sólo cabe, sino que se impone como obligación, desde que nos colocamos bajo las dos columnas “B” y “J” que dicen: “CIENCIA y VIRTUD”: ciencia libre de escolasticismos y exenta de sistemáticos prejuicios, y virtud sin mentida hipocresía ni alardes vanos.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Y en qué ayudáis además a los Maestros?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.',
     text:'En orientar a los AApr∴ no con palabras, no con discursos que se olvidan, sino con nuestro recto ejemplo, que es el que debe servir de lección a ellos; así es como está más comprometida nuestra dignidad de CComp∴ MMas∴, y así es como más está elevada nuestra misión de responsabilidad y nuestro deber de conducta.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'P.', text:'¿Cuántas preguntas se hacen para abrir o cerrar la Log∴ de Comp∴?'},
    {type:'dialogo', roles:['CAND'], speakerLabel:'R.', text:'Cinco, dirigidas alternativamente a los dos VVIg∴'}
  ]
},

/* ============ FASE 7: clausura / vuelta a aprendiz ============ */
{
  id:'clausura',
  title:'7. Clausura de los Trabajos de Compañero o Vuelta a los de Aprendiz',
  entries:[
    {type:'accion', roles:['VM'], text:'Opción A — Si se cierran definitivamente los trabajos de Compañero:'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Qué edad tenéis como Comp∴ H∴ Prim∴ Vig∴?'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Cinco años, Muy Ven∴ Maest∴'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven Maest∴', text:'¿Porqué esa edad, H∴ Seg∴ Vig∴?'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴',
     text:'Para expresar los años de estudio que en tiempo de la fundación de la Masonería intelectual eran indispensables para la adquisición de los conocimientos que el grado exigía.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿A qué tendían esos estudios H∴ Prim∴ Vig∴?'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴',
     text:'A llegar a ser inteligente, recto, valiente, prudente y filántropo; a cuyo empeño hoy nos dedicamos, bastándonos para emprender la noble faena, los conocimientos de la época en que vivimos, si tenemos buena voluntad y esfuerzo para conseguir el fin.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿A qué hora acostumbran los CComp∴ MMas∴ cerrar sus trabajos, H∴ Seg∴ Vig∴?'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴', text:'A media noche.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'¿Qué hora es, H∴ Prim∴ Vig∴?'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Media noche en punto.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Pues si es media noche, y la hora en que los CComp∴ MMas∴ acostumbran cerrar sus trabajos, servíos, HH∴ Prim∴ y Seg∴ VVig∴ Anunciar a los que decoran vuestras CCol∴ como yo lo hago a los de Or∴ que voy a terminar los de esta Seg∴ Cámara por los golpes y signos misteriosos.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴',
     text:'H∴ Seg∴ Vig∴ y HH∴ que decorais la Col∴ Del Sur, nuestro Muy Ven∴ Maest∴ nos anuncia que va a cerrar los trabajos de esta Log∴ por los golpes y signos misteriosos.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴',
     text:'HH∴ de mi columna, nuestro Muy Ven∴ Maest∴ declara que va a terminar los trabajos de esta Cám∴ Por los golpes y signos.'},
    {type:'accion', roles:['P2V'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Anunciado, Muy Ven∴ Maest∴'},
    {type:'accion', roles:['P1V'], text:'Da otro golpe de mallete.'},
    {type:'accion', roles:['VM','TODOS'], text:'El Muy Ven∴ Maest∴ da los golpes del grado y todos se ponen en pie y al orden.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Están cerrados los trabajos de Comp∴ a mí, HH∴'},
    {type:'accion', roles:['TODOS'], text:'Signo y batería, con la frase de:'},
    {type:'dialogo', roles:['TODOS'], speakerLabel:'Todos los HH∴', text:'¡Quien ilumina nuestra mente, Viva, Viva y siempre Viva!'},

    {type:'accion', roles:['VM'], text:'Opción B — Si en vez de clausurar se retorna a los trabajos de Aprendiz:'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Sentaos HH∴, y vos H∴ Guard∴ Temp∴ servíos avisar al Guard∴ Temp∴ Ext∴ que han acabado los trabajos de Comp∴ y que volveremos a los de Apr∴, en consecuencia, que entren los del Gr∴'},
    {type:'accion', roles:['GT'], loc:'Puerta del Templo, hacia el exterior y de vuelta con los Aprendices',
     text:'El Guarda Templo sale, avisa al Guarda Templo Exterior, vuelve con los Aprendices, quienes ocupan su columna, y cierra la puerta.'},
    {type:'dialogo', roles:['GT'], speakerLabel:'Guard∴ Temp∴', text:'Vuestra orden esta cumplida Muy Ven∴ Maest∴ , podemos proceder.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴',
     text:'Gracias H∴ -HH∴ Prim∴ Y Seg∴ VVIg∴ Servíos pedir a los de vuestras CCol∴ respectivas, como yo a los de Or∴ se unan a vosotros y a mí para continuar los trabajos de Apr∴que estaban suspensos.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴',
     text:'H∴ Seg∴ Vig∴ y HH∴ de mi Col∴ nuestro Muy Ven∴ Maest∴ os pide nos ayudeis a continuar los trabajos de Apr∴ Que estaban suspensos.'},
    {type:'dialogo', roles:['P2V'], speakerLabel:'Seg∴ Vig∴',
     text:'HH∴ de mi Col∴ nuestro Muy Ven∴ Maest∴ os pide nos ayudeis a continuar los trabajos de Apr∴ Que estaban suspensos. Anunciado H∴ Prim∴ Vig∴'},
    {type:'accion', roles:['P2V'], text:'Da un golpe de mallete.'},
    {type:'dialogo', roles:['P1V'], speakerLabel:'Prim∴ Vig∴', text:'Anunciado, Muy Ven∴ Maest∴'},
    {type:'accion', roles:['P1V'], text:'Da otro golpe de mallete.'},
    {type:'accion', roles:['VM','TODOS'], text:'El Muy Ven∴ Maest∴ da tres golpes de mallete y todos se paran.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'A mí HH∴'},
    {type:'accion', roles:['TODOS'], text:'Signos y baterías.'},
    {type:'dialogo', roles:['VM'], speakerLabel:'Muy Ven∴ Maest∴', text:'Los trabajos de Apr∴ están en actividad, Sentaos, HH∴'},
    {type:'accion', roles:['VM'], text:'Se despachan los negocios pendientes, se concede la palabra si antes no se había hecho, se corre el saco de Beneficencia, y se cierran los trabajos como se explicó en la liturgia de Aprendiz.'}
  ]
}

];
